<?php
date_default_timezone_set("Africa/Lagos");

$server_name = $_SERVER["SERVER_NAME"];
$dir_addition = "/blockchainrestore/";
$directory = (isset($_SERVER["HTTPS"]) ? "https" : "http") . "://" . $server_name . $dir_addition;
function directory() {
global $directory;
echo $directory;
}
$domain = "blockchainrestore.com";
$gen_name = "Blockchain Restore";
$full_gen_name = "Blockchain Restore";
$gen_email = "contact@blockchainrestore.com";
$gen_phone = "+1 (601) 349-1832";
$date = date("Y-m-d");
$date_time = date("Y-m-d H:i:s");
$ticket_id = date("YmdHis");
$rand_no = rand(1000,9999);
$foot_note = "<b>Note:</b> This email is autogenerated. Please do not reply.";
$regards = "<p>&nbsp;</p><p>Regards,<br>{$gen_name} Team.</p>";
$images = "images/";
$error = 1;
$rand = rand(1001,9999);
$actual_link = (isset($_SERVER['HTTPS']) ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

function new_version($file_name){
global $dir_addition;
$file_name = $dir_addition . $file_name;
if(strpos($file_name, '/') !== 0 || !file_exists($_SERVER['DOCUMENT_ROOT'] . $file_name))
return $file_name;	
$mtime = filemtime($_SERVER['DOCUMENT_ROOT'] . $file_name);
return (strlen($dir_addition) > 1)?str_replace($dir_addition, "", preg_replace('{\\.([^./]+)$}', ".$mtime.\$1", $file_name)) : substr(preg_replace('{\\.([^./]+)$}', ".$mtime.\$1", $file_name),1);
}

function test_input($data) {
$data = trim($data);
$data = preg_replace('/\s+/', ' ', $data);
$data = accepted_elements($data);
$data = htmlentities($data, ENT_QUOTES);
return $data;
}
function tp_input($data) {
$data = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]))?test_input($_POST[$data]):"";
return $data;
}
function np_input($data) {
$data = ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]))?testQty($_POST[$data]):"";
return $data;
}
function tr_input($data) {
$data = (isset($_REQUEST[$data]) && !empty($_REQUEST[$data]))?test_input($_REQUEST[$data]):"";
return $data;
}
function nr_input($data) {
$data = (isset($_REQUEST[$data]) && !empty($_REQUEST[$data]))?testQty($_REQUEST[$data]):"";
return $data;
}
function check_inputted($data="", $sub_data = ""){
global $error;
echo ($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]) && $error == 1)?trim($_POST[$data]):$sub_data;
}
function check_checked($data="", $sub_data = "", $main_data = ""){
global $error;
echo ((($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]) && $_POST[$data] == $sub_data) or (empty($_POST[$data]) && $main_data == $sub_data)) && $error == 1)?" checked":"";
}
function check_selected($data = "", $sub_data = "", $main_data = ""){
global $error;
echo ((($_SERVER["REQUEST_METHOD"] == "POST" && !empty($_POST[$data]) && $_POST[$data] == $sub_data) or (empty($_POST[$data]) && $main_data == $sub_data)) && $error == 1)?" selected":"";
}
function current_page($data){
$result = (basename($_SERVER["PHP_SELF"]) == "{$data}.php")?"current":"";
return $result;
}
function date_valid($date){
if(strpos($date,"-") > 0){
$date_array = explode("-",$date);
$day = (int) $date_array[2];
$month = (int) $date_array[1];
$year = (int) $date_array[0];
$det_date = checkdate($month, $day, $year);
if ($det_date){
return TRUE; 
}else{
return FALSE;
}
}else{
return FALSE;
}
}

function seo_link($data) {
$data = html_entity_decode($data,ENT_QUOTES);
$data = strip_tags($data);
$data = trim($data);
$data = strtolower($data);
$data = preg_replace("/\s+/", " ", $data);
$data = preg_replace("#[^0-9a-z' ]#i", "", $data);
$data = str_replace(" ","-", $data);
return $data;
}
function title_link($data) {
$data = html_entity_decode($data,ENT_QUOTES);
$data = strip_tags($data);
$data = trim($data);
$data = preg_replace("/\s+/", " ", $data);
$data = str_replace("-"," ", $data);
$data = preg_replace("#[^0-9a-z' ]#i", "", $data);
$data = $data . " ";
$data_array = explode(" ",$data);
$data = "";
foreach($data_array as $value){
if(!empty($value)){
$data = $data . ucfirst($value) . " ";
}
}
$data = trim($data);
return $data;
}

function redirect($filename){
if(!headers_sent()){
header('Location: '.$filename);
}else{
?>
<script type="text/javascript">
<!--
window.location.href="<?php echo $filename; ?>";
//-->
</script>
<noscript>
<meta http-equiv="refresh" content="0;url=<?php echo $filename; ?>" />
</noscript>
<?php
}
}

///=========================Mail Functions===========//////
function message_template(){
global $subject, $message, $foot_note, $regards, $directory, $domain, $gen_email, $gen_phone, $images;
$result = "
<html>
<head>
<title>{$subject}</title>
</head>
<body>

<div style=\"background:#f9f9f9 !important; padding:10px !important; font-family:Arial, Helvetica, sans-serif; font-size:16px !important;\">
<div style=\"margin:auto !important; width:100% !important; max-width:800px !important;\">

<div style=\"min-height:300px !important; padding:10px !important; background:#fff !important;\">
{$message}
{$regards}
</div>

<p style=\"font-size:14px !important;\">
<span style=\"font-weight:bold !important;\">Email:</span> {$gen_email},<br>
<span style=\"font-weight:bold !important;\">Phone:</span> {$gen_phone},<br>
<span style=\"font-weight:bold !important;\">Website:</span> <a href=\"{$directory}\" style=\"color:#f33 !important; text-decoration:none !important;\">{$domain}</a>.
</p>";
$result .= (!empty($foot_note))?"<p style=\"background:#ddd !important;font-size:12px !important; padding:10px !important; overflow:hidden !important;\">{$foot_note}</p>":"";
$result .= "</div>
</div>

</body>
</html>";
return $result;
}

function send_mail($no=""){
global $to, $subject, $message, $headers, $gen_email;

$message = wordwrap($message,70);
// Always set content-type when sending HTML email
$headers2 = $headers;
$headers = "MIME-Version: 1.0" . "\r\n";
$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
$headers .= "From: {$headers2}" . "\r\n";
$headers .= ($no == 1)?"BCC: {$gen_email}" . "\r\n":"";

$result = mail($to,$subject,$message,$headers);
return $result;
}


///================Detect Browser===================///////
function det_browser($data){
global $detect;
$result = "";
$result = ( $detect->isMobile() && !$detect->isTablet() ) ? "" : $data;
return $result;
}

function accepted_elements($data){
$value = str_replace("strong>", "b>", $data);
$value = str_replace("em>", "i>", $value);
$value = strip_tags($value,"<img><b><i><u><a><br><ol><ul><li><p><code><table><thead><tbody><tr><th><td><h1><h2><h3><h4><h5><h6><blockquote><hr><s>");
return $value;
}

function break_long($data, $prefix="", $suffix=""){
$broken_data = $prefix . wordwrap($data, 15, "<br />", true) . $suffix;
return $broken_data;
}

function decode_content($data){
return html_entity_decode($data, ENT_QUOTES);
}

function testTotal($amount){
$amountReturn = preg_replace('#[^0-9.]#i', '', $amount);
$amountReturn = test_input($amountReturn);
$amountReturn = str_replace(",","",$amountReturn);
$amountReturn = str_replace("-","",$amountReturn);
$amountPos = strpos($amountReturn,".");
if($amountPos > 0){
$amountReturn = substr($amountReturn,0,$amountPos+3);
}
return $amountReturn;
}

function testQty($amount){
$amountReturn = preg_replace('#[^0-9]#i', '', $amount);
$amountReturn = test_input($amountReturn);
$amountReturn = str_replace(",","",$amountReturn);
$amountReturn = str_replace("-","",$amountReturn);
$amountPos = strpos($amountReturn,".");
if($amountPos > 0){
$amountReturn = substr($amountReturn,0,$amountPos);
}
return $amountReturn;
}

function formatNumber($amount){
$amountOriginal = "{$amount}";
if($amountOriginal != ""){
$sign_left = ($amountOriginal < 0)?"(":"";
$sign_right = ($amountOriginal < 0)?")":"";
$amountOriginal = $sign_left . number_format(abs($amountOriginal), 2, '.', ',') . $sign_right;
}
return $amountOriginal;
}

function formatQty($amount){
$amountOriginal = "{$amount}";
if($amountOriginal != ""){
$amountOriginal = number_format($amountOriginal, 0, '', ',');
}
return $amountOriginal;
}
?>